flaskProject/app/models.py
from flask_login import UserMixin
from flask import current_app
from flask_mongoengine import MongoEngine
from app import login_manager

db = MongoEngine()

class DocStored(db.Document):
    '''class for define structure of each document'''
    docId = db.StringField(required = True)
    language = db.StringField(required = True)
    year = db.IntField(required=True)
    fullText = db.StringField(required=True)

    meta = {
        'collection': 'documentsTest',  # collection name
        'ordering': ['-score'],  # default ordering
        'auto_create_index': False,  # MongoEngine will not create index
    }

class User(UserMixin,db.Document):
    meta = {'collection': 'Users'}
    email = db.StringField(max_length=30)
    password = db.StringField()

@login_manager.user_loader
def load_user(user_id):
    return User.objects(pk=user_id).first()

flaskProject/app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectField, SubmitField

class SelectCountryForm(FlaskForm):
    country =  SelectField(u"Select Country",choices = [("EN-GB","English")])
    submit = SubmitField("Load Documents")

flaskProject/app/ETL/__init__.py
import os
import glob
from flask import Blueprint
__all__ = [os.path.basename(f)[:-3]
    for f in glob.glob(os.path.dirname(__file__) + "/*.py")]

sim_bp = Blueprint('similarity', __name__)
db_bp = Blueprint('database',__name__)

from app.ETL import similarity
from app.ETL import dataBase

flaskProject/app/__init__.py
import os

from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_mongoengine import MongoEngine
from flask_debugtoolbar import DebugToolbarExtension
from flask_wtf.csrf import CSRFProtect

import config
## include db name in URI; _HOST entry overwrites all others

login_manager = LoginManager()

csrf = CSRFProtect()

def create_app():
    app = Flask(__name__, instance_relative_config=True)
    app.config['DEBUG_TB_PANELS'] = ['flask_mongoengine.panels.MongoDebugPanel']


    #app.config['MONGODB_SETTINGS'] = {'host':config.Config.MONGODB_HOST_LOCAL}
    app.config['MONGODB_SETTINGS'] = {'db': config.Config.MONGODB_DATABASE,
                                      'host': config.Config.MONGODB_HOST,
                                      'port': config.Config.MONGODB_PORT,
                                      'username': config.Config.MONGODB_USERNAME,
                                      'password': config.Config.MONGODB_PASSWORD
                                      }
    app.config['SECRET_KEY'] = config.Config.SECRET_KEY

    #It connects but no replicaset
    app.debug = False
    # initalize app with database
    Bootstrap(app)

    #initialize protecction
    csrf.init_app(app)
    from .models import db
    db.init_app(app)
    DebugToolbarExtension(app)
    login_manager.init_app(app)
    login_manager.login_message = "You must be logged in to access this page."
    login_manager.login_view = "auth.login"


    #if test_config is None:
        #load the instance config, if it exists, when no testing
    #    app.config.from_pyfile('config.py', silent=True)
    #else:
        #load the test config if passed in
        #app.config.from_mapping(test_config)


    from app import models
    
    from app.ETL import sim_bp as sim_bp, db_bp as db_bp
    from .auth import auth_bp as auth_blueprint
    from .home import home_bp as home_blueprint
    app.register_blueprint(sim_bp)
    app.register_blueprint(db_bp)
    app.register_blueprint(auth_blueprint)
    app.register_blueprint(home_blueprint)


    return app

flaskProject/app/home/__init__.py
from flask import Blueprint

home_bp = Blueprint('home', __name__)

from . import views

flaskProject/app/home/views.py
from flask import render_template, json, request,jsonify
from mongoengine.context_managers import switch_collection
import pandas as pd
from flask_login import login_required
from .forms import SelectCountryForm

from . import home_bp
from ..models import User, DocStored
from ..ETL import similarity

df = pd.DataFrame()

@home_bp.route("/")
def homepage():
    """
    Render the homepage template on the / route
    :return:
    """
    return render_template("home/index.html",title="Welcome")

@home_bp.route("/dashboard", methods=['GET','POST'])
@login_required
def dashboard():
     """
     Render the dashboard template on the dashboard route
     :return:
     """
     form = SelectCountryForm()
     return render_template("home/dashboard.html",form = form, title="Dashboard")


@home_bp.route("/loadDocs", methods=['GET', 'POST'])
@login_required
def loadDocs():
     '''
     Load documents from database
     :return:
     '''
     #test = True
     try:
         if request.method == "POST":
             if (request.form.get('env') == "test"):
                 with switch_collection(DocStored, 'documentsTest') as Doc:
                     #return request.form.get('country')
                     #allDocs = json.dumps(Doc.objects())
                     allDocs = json.dumps(Doc.objects(language=request.form.get('country')))
             else:
                 with switch_collection(DocStored, 'documents') as Doc:
                     #allDocs = json.dumps(Doc.objects(language=request.form.get('country'))[:15])
                     year2Search = int(request.form.get('year'))
                     allDocs = json.dumps(Doc.objects(language=request.form.get('country'), year = year2Search))

             global df
             df = pd.read_json(allDocs)
             count_row = df.shape[0]
             return str(count_row)
                    #+ str(request.form.get('env') )
         else:
             return str(-2)
     except Exception as e:
        return "Error \n %s" % (e)


@home_bp.route("/findSimilarity", methods=['GET', 'POST'])
@login_required
def findSimilarity():
     '''
     Find similarity between documents
     :return: Array of similar documents
     '''
     global df
     try:
         if request.method == "POST":
             if request.form.get('text2Compare'):
                 simTool = similarity.textSimilarity()
                 arrResults = simTool.getCosineText(df,request.form.get('text2Compare'),4)
                 return jsonify(resultsArray=arrResults)
             else:
                 return 'Wrong parameters'
         else:
             return "Wrong method"
     except (ValueError, KeyError, TypeError):
         return str(ValueError) + str(KeyError) + str(TypeError)


@home_bp.route("/checkDocuments", methods=['GET', 'POST'])
@login_required
def checkDocuments():
     '''
     show a screen with two documents
     :return:
     '''
     return render_template("home/checkDocuments.html", title="CheckingDocs", text1="Not valid solutions", text2="text2")

flaskProject/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ title }} | SimText Project</title>
    <link href="{{ url_for('static', filename='css/bootstrapmin.css') }}" rel="stylesheet">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
</head>
<body>
    <script type="text/javascript">
  $(document).ready(function(){
    $linkLoadDocs= "{{ url_for('home.loadDocs') }}";
    $linkSimilarity= "{{ url_for('home.findSimilarity') }}";
    $csrf_token = "{{ csrf_token() }}";
    $linkcheckDocuments = "{{ url_for('home.checkDocuments') }}";
  })
  </script>
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand topnav" href="{{ url_for('home.homepage') }}">SimText Project</a>
          </div>
          <ul class="nav navbar-nav navbar-right">
              {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('home.dashboard') }}">Dashboard</a></li>
                <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                <li><a><i class="fa fa-user"></i>  Hi, {{ current_user.email }}!</a></li>
              {% else %}
                <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
                <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                <li><a href="{{ url_for('auth.login') }}">Login</a></li>
              {% endif %}
          </ul>
        </div>
    </nav>
    <div class="wrapper">
      {% block body %}
      {% endblock %}
    </div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
                        <li class="footer-menu-divider">⋅</li>
                        {% if current_user.is_authenticated %}
                          <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                        {% else %}
                          <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                          <li class="footer-menu-divider">⋅</li>
                          <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                        {% endif %}
                    </ul>
                    <p class="copyright text-muted small">TFM by Miguel Garcia Ibañez</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

flaskProject/app/templates/base2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

flaskProject/app/templates/baseFlex.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ title }} | SimText Project</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <link href="{{ url_for('static', filename='css/styleFlex.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
</head>
<body class="HolyGrail">
  <header></header>
  <div class="HolyGrail-body">
    <main class="HolyGrail-content">
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </main>
    <nav class="HolyGrail-nav">

         <div class="container topnav">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand topnav" href="{{ url_for('home.homepage') }}">SimText Project</a>
          </div>
          <ul class="nav navbar-nav navbar-right">
              {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('home.dashboard') }}">Dashboard</a></li>
                <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                <li><a><i class="fa fa-user"></i>  Hi, {{ current_user.email }}!</a></li>
              {% else %}
                <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
                <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                <li><a href="{{ url_for('auth.login') }}">Login</a></li>
              {% endif %}
          </ul>
        </div>

    </nav>
  </div>
  <footer>
      <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
                        <li class="footer-menu-divider">⋅</li>
                        {% if current_user.is_authenticated %}
                          <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                        {% else %}
                          <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                          <li class="footer-menu-divider">⋅</li>
                          <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                        {% endif %}
                    </ul>
                    <p class="copyright text-muted small">TFM by Miguel Garcia Ibañez</p>
                </div>
            </div>
        </div>
  </footer>
</body>
<!--<body>
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand topnav" href="{{ url_for('home.homepage') }}">SimText Project</a>
          </div>
          <ul class="nav navbar-nav navbar-right">
              {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('home.dashboard') }}">Dashboard</a></li>
                <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                <li><a><i class="fa fa-user"></i>  Hi, {{ current_user.email }}!</a></li>
              {% else %}
                <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
                <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                <li><a href="{{ url_for('auth.login') }}">Login</a></li>
              {% endif %}
          </ul>
        </div>
    </nav>
    <div class="wrapper">
      {% block body %}
      {% endblock %}
    </div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
                        <li class="footer-menu-divider">⋅</li>
                        {% if current_user.is_authenticated %}
                          <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                        {% else %}
                          <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                          <li class="footer-menu-divider">⋅</li>
                          <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                        {% endif %}
                    </ul>
                    <p class="copyright text-muted small">TFM by Miguel Garcia Ibañez</p>
                </div>
            </div>
        </div>
    </footer>
</body>
-->
</html>

flaskProject/app/templates/home/checkDocuments.html
<!-- app/templates/home/dashboard.html -->

{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Check documents{% endblock %}
{% block body %}
<div class="content-section">
  <div class="center">
    <div class="shadow"><img class="logo" src="../static/img/ajax-loader.gif" /></div>
    <div class="container-body">
        <div class="dashboard-content">
            <textarea class="txta-small" name="t1" id="t1">{{ text1 }}</textarea>
        </div>
       <div class="dashboard-content">
            <textarea class="txta-small" name="t2" id="t2">{{ text2 }}</textarea>
        </div>
    </div>
    <div class="container-button">
        <input class="btn btn-default" id="findSim" name="find" type="submit" value="Find Similarity">
    </div>
  </div>
  <script type="text/javascript" src="../static/dashboard.js">
</script>
</div>
{% endblock %}

flaskProject/app/templates/home/dashboard.html
<!-- app/templates/home/dashboard.html -->

{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block body %}
<div class="content-section">
  <div class="center">
    <div class="shadow"><img class="logo" src="../static/img/ajax-loader.gif" /></div>
    <label>Select Country and Environment</label>
     <div class="form form-inline" role="">
        <div class="form-group ">
          <select class="form-control" id="country" name="country"><option value="EN-GB">English</option></select>
          <select class="form-control" id="env" name="env"><option value="test">Test</option><option value="prod">Production</option></select>
          <select class="form-control" id="year" name="year">
              <option value="2007">2007</option>
              <option value="2008">2008</option>
              <option value="2009">2009</option>
              <option value="2010">2010</option>
              <option value="2011">2011</option>
              <option value="2012">2012</option>
              <option value="2013">2013</option>
              <option value="2014">2014</option>
              <option value="2015">2015</option>
              <option value="2016">2016</option>
          </select>
        </div>
        <input class="btn btn-default" id="submit" name="submit" type="submit" value="Load Documents">
        <label class="doc-info"></label>
        <input type="checkbox" id="setText" class="setText" value="setText"> <label for="setText">Set Example Text</label>
    </div>
    <div class="container-body">
        <div class="dashboard-content">
            <textarea class="txta-small" id="t1" name="t1">Paste your text and click on Find Similarity</textarea>
        </div>
         <div class="dashboard-content" id="hiddenText">
            <textarea class="txta-small" name="t2" id="t2">{{ text2 }}</textarea>
        </div>
        <div class="dashboard-content-left">
            <div class="Table">
              <div class="Table-header">
                <div class="Table-row-item">Document Id</div>
                <div class="Table-row-item">Similarity %</div>
                <div class="Table-row-item">Text</div>
                <div class="Table-row-item">Compare</div>
              </div>
            </div>
        </div>
    </div>
    <div class="container-button">
        <input class="btn btn-default" id="findSim" name="find" type="submit" value="Find Similarity">
    </div>
  </div>
  <script type="text/javascript" src="../static/dashboard.js">
</script>
</div>
{% endblock %}

flaskProject/app/templates/home/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>SimText Project</h1>
                    <h3>Your comparator of laws</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

flaskProject/app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Checking</title>
</head>
<body>
    WTF
</body>
</html>